### ISSUE TITLE
del_to and del_from no longer works

### ISSUE THREAD

**Issue by chocopepper** [SpEcHiDe/DeleteMessagesRoBot#17]
Function del_to and del_from seems outdated and not works anymore.
Could you please update the code to make it work again?

**Comment by SpEcHiDe** [comment]
Any screenshot OR logs what you tried ?

**Comment by SpEcHiDe** [comment]
Works Fine

![](https://te.legra.ph/file/b907ddbeddd886e0d9d76.jpg)

![](https://te.legra.ph/file/c10a3cb2d8848073bdcc3.jpg)
