### ISSUE TITLE
#Request For Features

### ISSUE THREAD

**Issue by MaxxRider** [SpEcHiDe/DeleteMessagesRoBot#3]
Sir,
 Please Add in README your 
upcoming TO-DO on this Repo🤪🤪

Can we expect another features in Future Update For  unlimited Deleted Validity  🤒
because last 48 hours Message Not Enough 😰😰

if possible please Increased 48 hours to atleast 7 days 🤩🤩

**Comment by SpEcHiDe** [comment]
![IMG_20201026_155805_554](https://user-images.githubusercontent.com/6317196/97161589-0d4a9880-17a4-11eb-8cbf-bde8a21a9488.jpg)

Please don't spam with same closed issues. ☹️☹️😁

**Comment by MaxxRider** [comment]
🙁😑😑😁😁😁😁

🤭🤭
