### ISSUE TITLE
Bot Isn't Deleting Messages Anymore

### ISSUE THREAD

**Issue by FristyFlakes** [SpEcHiDe/DeleteMessagesRoBot#6]
Started A Few Days Back, Given All Permissions Correctly Yet It Doesn't Delete Anything, User Joins & Leaves Without Anything Carried Out

**Comment by SpEcHiDe** [comment]
Which bot are you trying to run? I don't run any Telegram bots using this repository code.

**Comment by FristyFlakes** [comment]
I mean the repo stopped working. It isn't deleting anything anymore
