### ISSUE TITLE
Not working now 

### ISSUE THREAD

**Issue by Ashish07143** [SpEcHiDe/DeleteMessagesRoBot#8]
It is not working sir I am attaching here the logs 
I did everything correctly u can check once by looking logs attached 

Also sent to your telegram 
From this @edofox_ceo
@SpEcHiDe check it 
![Screenshot_2021-05-30-15-51-07-946_com mycompany app soulbrowseo](https://user-images.githubusercontent.com/54226280/120103124-b8249a00-c16b-11eb-90fa-96475860a87f.jpg)
![Screenshot_2021-05-30-15-51-15-472_com mycompany app soulbrowseo](https://user-images.githubusercontent.com/54226280/120103128-bd81e480-c16b-11eb-860d-266251acb0e8.jpg)

**Comment by SpEcHiDe** [comment]
you used TeleThon string session instead of Pyrogram String Session.

**Comment by Ashish07143** [comment]
But your string session not working that time so use another one from Google 
Can u give one which session will work here 🥲

**Comment by SpEcHiDe** [comment]
just use any bots in the #7 if you cannot create your own bot, after watching the YouTuBe video.
